### PR TITLE
WIP: 113/skip turn

### PR DESCRIPTION
**Pull request by bronvic**
Solves #113 
This pull request introduces [new command](https://github.com/Miol-Mor/battle-game/wiki/Web-socket-messages#skip). Users can skip there turn instead of moving or attacking

This is still work in progress because ui widget does not implemented. However, you can test this by executing `game.process_skip_turn()` from web console

### CODE REVIEW

**Comment by bronvic** [comment]
Skip turn button has been added

However, there are some bugs: 
* selected unit does not stop pulsing
* backend and frontend become out of sync when you skip turn after move without attack

Need to test it manually and kill all bugs

**Review by Hairash — CHANGES_REQUESTED** [review]
Tests needed

**Comment by bronvic** [comment]
Bug, mentioned [here](https://github.com/Miol-Mor/battle-game/pull/149#issuecomment-766111008) was [fixed](https://github.com/Miol-Mor/battle-game/pull/149/commits/f7f25e5b7912497464d3dba7c3f4fce95c9f200a#diff-025afee13187fe66fb9218c9a22dd0bca4e809822395df3681651d1a2d131f6eR233)

**Comment by bronvic** [comment]
Still [struggling](https://stackoverflow.com/questions/66124951/testing-rust-actix-messages-that-sends-via-actors) with tests

**Review by Hairash — APPROVED** [review]

**Pull request merged**
